/* Auto-generated by scripts/sync-substack-posts.mjs. */
export type SubstackPost = {
  postId: number;
  title: string;
  subtitle: string | null;
  excerpt: string;
  publishedAt: string | null;
  sourceUrl: string;
  canonicalUrl: string;
};

export const substackPosts: SubstackPost[] = [
  {
    "postId": 192200914,
    "title": "Technical writer is the wrong job title",
    "subtitle": "The augmentation debate is a distraction",
    "excerpt": "The question everyone’s asking is whether AI will replace technical writers. It’s the wrong question, and answering it either way tends to obscure what’s actually at stake.",
    "publishedAt": "2026-03-26T15:34:33.870Z",
    "sourceUrl": "https://substack.com/home/post/p-192200914",
    "canonicalUrl": "https://mattgourd.substack.com/p/technical-writer-is-the-wrong-job"
  },
  {
    "postId": 191669442,
    "title": "OpenClaw in the wild",
    "subtitle": "The gap between running and safe to run",
    "excerpt": "Most people who set up OpenClaw this month did the same thing. Installed it, connected it to Telegram or WhatsApp, sent themselves a message from another room, felt the mild electricity of that working, and moved on.",
    "publishedAt": "2026-03-21T13:01:51.194Z",
    "sourceUrl": "https://substack.com/home/post/p-191669442",
    "canonicalUrl": "https://mattgourd.substack.com/p/openclaw-in-the-wild"
  },
  {
    "postId": 191499411,
    "title": "Nostalgia dressed as a standard",
    "subtitle": "Before we criticise vibe coding for being messy, let's look inside a Word document.",
    "excerpt": "It gets said with the weariness of someone who’s been around long enough to know better. That weariness is usually the tell. Vibe coding is messy. The output is unreadable. No serious engineer would produce that.",
    "publishedAt": "2026-03-19T19:05:43.653Z",
    "sourceUrl": "https://substack.com/home/post/p-191499411",
    "canonicalUrl": "https://mattgourd.substack.com/p/nostalgia-dressed-as-a-standard"
  },
  {
    "postId": 191342672,
    "title": "The idea is the easy part",
    "subtitle": "LLMs can't think outside the box.",
    "excerpt": "It’s said with the confidence of something that doesn’t need proving, usually by people who haven’t looked at the research, occasionally by people who have looked at half of it and stopped at the finding that suited them. Either way, it closes conversations...",
    "publishedAt": "2026-03-18T07:44:08.063Z",
    "sourceUrl": "https://substack.com/home/post/p-191342672",
    "canonicalUrl": "https://mattgourd.substack.com/p/the-idea-is-the-easy-part"
  },
  {
    "postId": 188512784,
    "title": "Expertise doesn't grow on trees",
    "subtitle": "Just a thought for a Thursday afternoon.",
    "excerpt": "I’ve been thinking about something that hardly anyone seems to be talking about.\n\nAI is quietly eating junior jobs. Not in a dramatic, robots-taking-over kind of way. More like a slow tide going out. Why hire a junior writer to produce the first draft when the AI does...",
    "publishedAt": "2026-02-19T16:32:35.280Z",
    "sourceUrl": "https://substack.com/home/post/p-188512784",
    "canonicalUrl": "https://mattgourd.substack.com/p/expertise-doesnt-grow-on-trees"
  },
  {
    "postId": 185519390,
    "title": "The birth of the agentic technical writer",
    "subtitle": "From prompts to pipelines: how technical writers become AI workflow designers.",
    "excerpt": "We’re witnessing a fundamental shift in technical communication and it’s not what you think.\n\nAgentic AI isn’t just another tool to learn. It’s a complete reimagining of how content work gets done.",
    "publishedAt": "2026-01-23T09:39:51.664Z",
    "sourceUrl": "https://substack.com/home/post/p-185519390",
    "canonicalUrl": "https://mattgourd.substack.com/p/the-birth-of-the-agentic-technical"
  }
];
